# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guruapp', '0002_auto_20160419_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationspamvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guruapp.Recommendation'),
        ),
    ]
