# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruapp', '0005_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
