# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruapp', '0007_auto_20160502_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
